// <auto-generated />
using System;
using Managment;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Test.Migrations
{
    [DbContext(typeof(ManagmentContext))]
    [Migration("20221025190439_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Managment.Models.EmployeeBasicData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheRoleOff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeBasicDataSet");
                });

            modelBuilder.Entity("Managment.Models.EmployeeExtensionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ActuallProjectId")
                        .HasColumnType("int");

                    b.Property<int>("DaysOfVacation")
                        .HasColumnType("int");

                    b.Property<int>("DaysOfVacationLeft")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MounthsInWork")
                        .HasColumnType("int");

                    b.Property<int>("PaymentGross")
                        .HasColumnType("int");

                    b.Property<int>("PaymentNet")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActuallProjectId");

                    b.HasIndex("EmployeId");

                    b.ToTable("EmployeeExtensionDataSet");
                });

            modelBuilder.Entity("Managment.Models.ProjectsData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClientNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Complited")
                        .HasColumnType("bit");

                    b.Property<int>("Costs")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagerOfProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotentialProfit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManagerOfProjectId");

                    b.ToTable("ProjectsDataSet");
                });

            modelBuilder.Entity("Managment.Models.EmployeeExtensionData", b =>
                {
                    b.HasOne("Managment.Models.ProjectsData", "ActuallProject")
                        .WithMany()
                        .HasForeignKey("ActuallProjectId");

                    b.HasOne("Managment.Models.EmployeeBasicData", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeId");

                    b.Navigation("ActuallProject");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Managment.Models.ProjectsData", b =>
                {
                    b.HasOne("Managment.Models.EmployeeBasicData", "ManagerOfProject")
                        .WithMany()
                        .HasForeignKey("ManagerOfProjectId");

                    b.Navigation("ManagerOfProject");
                });
#pragma warning restore 612, 618
        }
    }
}
